# Generated by Django 2.2.3 on 2019-08-30 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Representatives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('PC', models.IntegerField()),
                ('LR', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('PC', models.IntegerField()),
                ('LR', models.IntegerField()),
                ('representative', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Game.Representatives')),
            ],
        ),
    ]
