# Generated by Django 2.2.3 on 2019-09-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='representatives',
            name='player',
            field=models.IntegerField(default=0),
        ),
    ]
