# Generated by Django 2.2.3 on 2019-09-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_representatives_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamename', models.TextField()),
                ('turn', models.IntegerField(default=0)),
            ],
        ),
    ]
