# Generated by Django 2.2.3 on 2019-09-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0007_representatives_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='MessageMainScreen',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
