# Generated by Django 2.2.3 on 2019-09-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0008_general_messagemainscreen'),
    ]

    operations = [
        migrations.AddField(
            model_name='representatives',
            name='CountyElection',
            field=models.TextField(default=''),
        ),
    ]
