# Generated by Django 2.2.3 on 2019-09-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0010_auto_20190906_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representatives',
            name='CountyElection',
        ),
        migrations.AddField(
            model_name='representatives',
            name='Percentage',
            field=models.IntegerField(default=0),
        ),
    ]
