# Generated by Django 2.2.3 on 2019-09-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0011_auto_20190906_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='representatives',
            name='CountyElection',
            field=models.TextField(default=''),
        ),
    ]
