# Generated by Django 2.2.3 on 2019-09-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0012_representatives_countyelection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representatives',
            name='Percentage',
            field=models.FloatField(default=0),
        ),
    ]
