# Generated by Django 2.2.3 on 2019-09-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0013_auto_20190906_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='parties',
            name='Seats',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
