# Generated by Django 2.2.3 on 2019-09-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0015_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='Current_topic',
            field=models.BooleanField(default=True),
        ),
    ]
