# Generated by Django 2.2.3 on 2019-09-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0017_auto_20190910_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='MessageParliamentScreen',
            field=models.TextField(default='check'),
            preserve_default=False,
        ),
    ]
