# Generated by Django 2.2.3 on 2019-09-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0018_general_messageparliamentscreen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='general',
            old_name='Military',
            new_name='Community',
        ),
        migrations.RenameField(
            model_name='general',
            old_name='Taxes',
            new_name='Ethics',
        ),
        migrations.AddField(
            model_name='general',
            name='Immigration',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='general',
            name='Social_protection',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='general',
            name='Taxation',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='general',
            name='Worldview',
            field=models.IntegerField(default=50),
        ),
    ]
