# Generated by Django 2.2.3 on 2019-09-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0020_topics_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='Shift',
            field=models.IntegerField(default=10),
        ),
    ]
