# Generated by Django 2.2.3 on 2019-09-12 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0021_topics_shift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='general',
            old_name='MessageMainScreen',
            new_name='MessageCountiesScreen',
        ),
    ]
