# Generated by Django 2.2.3 on 2019-09-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0023_auto_20190914_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='general',
            name='turn',
        ),
        migrations.AddField(
            model_name='general',
            name='Status',
            field=models.TextField(default='Candidates'),
        ),
        migrations.AlterField(
            model_name='general',
            name='Community',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='general',
            name='Ethics',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='general',
            name='Immigration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='general',
            name='Nature',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='general',
            name='Social_protection',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='general',
            name='Taxation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='general',
            name='Worldview',
            field=models.IntegerField(default=0),
        ),
    ]
