# Generated by Django 2.2.3 on 2019-09-21 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0024_auto_20190921_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='general',
            old_name='gamename',
            new_name='Name',
        ),
    ]
