# Generated by Django 2.2.3 on 2019-09-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0026_remove_general_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='Status',
            field=models.TextField(default='Candidates'),
        ),
    ]
