# Generated by Django 2.2.3 on 2019-09-22 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0027_general_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='general',
            old_name='Status',
            new_name='Next_action',
        ),
    ]
