# Generated by Django 2.2.3 on 2019-09-24 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0029_parties_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topics',
            old_name='Vote',
            new_name='Proposal',
        ),
    ]
