# Generated by Django 2.2.3 on 2019-10-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0031_auto_20191007_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='CP_bar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='general',
            name='LR_bar',
            field=models.IntegerField(default=0),
        ),
    ]
