# Generated by Django 2.2.3 on 2019-10-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0036_parties_declaration_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='MessageGovernmentScreen',
            field=models.TextField(default='yes'),
            preserve_default=False,
        ),
    ]
