# Generated by Django 2.2.3 on 2019-10-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0037_general_messagegovernmentscreen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parties',
            name='Declaration_maker',
            field=models.TextField(default='No'),
        ),
    ]
