# Generated by Django 2.2.3 on 2019-10-12 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0041_auto_20191012_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parties',
            old_name='user',
            new_name='User',
        ),
    ]
