# Generated by Django 2.2.3 on 2019-10-12 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0044_auto_20191012_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='representatives',
            old_name='CountyElection',
            new_name='County_election',
        ),
    ]
