# Generated by Django 2.2.3 on 2019-10-12 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0045_auto_20191012_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='general',
            old_name='MessageCountiesScreen',
            new_name='Message_elections_page',
        ),
    ]
