# Generated by Django 2.2.3 on 2019-10-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0047_auto_20191012_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='Current_topic_1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='topics',
            name='Current_topic_2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='topics',
            name='Current_topic_3',
            field=models.BooleanField(default=True),
        ),
    ]
