# Generated by Django 2.2.3 on 2019-10-14 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0048_auto_20191014_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topics',
            name='CP',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='LR',
        ),
    ]
