# Generated by Django 2.2.3 on 2019-10-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0049_auto_20191014_0820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topics',
            old_name='Current_topic',
            new_name='Current_proposal',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='Current_topic_1',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='Current_topic_2',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='Current_topic_3',
        ),
        migrations.AddField(
            model_name='topics',
            name='Current_proposal_number',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
