# Generated by Django 2.2.3 on 2019-10-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0050_auto_20191014_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='parties',
            name='Vote_proposal_1',
            field=models.TextField(default='No'),
        ),
        migrations.AddField(
            model_name='parties',
            name='Vote_proposal_2',
            field=models.TextField(default='No'),
        ),
        migrations.AddField(
            model_name='parties',
            name='Vote_proposal_3',
            field=models.TextField(default='No'),
        ),
    ]
