# Generated by Django 2.2.3 on 2019-10-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0051_auto_20191014_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='parties',
            name='Expected_vote_proposal_1',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='parties',
            name='Expected_vote_proposal_2',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='parties',
            name='Expected_vote_proposal_3',
            field=models.TextField(default=None, null=True),
        ),
    ]
