# Generated by Django 2.2.3 on 2019-10-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0053_parties_made_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='parties',
            name='Deal_breaker',
            field=models.BooleanField(default=False),
        ),
    ]
