# Generated by Django 2.2.3 on 2019-10-16 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Game', '0054_parties_deal_breaker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Current', models.BooleanField(default=True)),
                ('Promised_vote_proposal_1', models.TextField()),
                ('Promised_vote_proposal_2', models.TextField()),
                ('Promised_vote_proposal_3', models.TextField()),
                ('Other_party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Game.Parties')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
