# Generated by Django 2.2.3 on 2019-10-16 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0055_deals'),
    ]

    operations = [
        migrations.AddField(
            model_name='deals',
            name='User_party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Game.Parties'),
        ),
        migrations.AlterField(
            model_name='deals',
            name='Other_party',
            field=models.TextField(default=''),
        ),
    ]
