# Generated by Django 2.2.3 on 2019-10-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0056_auto_20191016_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='counties',
            name='Spread',
            field=models.IntegerField(default=2),
        ),
    ]
