# Generated by Django 2.2.3 on 2019-10-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0058_general_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='Next_action',
            field=models.TextField(default='Submit candidates'),
        ),
    ]
