# Generated by Django 2.2.3 on 2019-10-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0059_auto_20191021_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='Year',
            field=models.IntegerField(default=1),
        ),
    ]
