# Generated by Django 2.2.3 on 2019-10-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0061_parties_next_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='Votes_against_proposal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='general',
            name='Votes_for_proposal',
            field=models.IntegerField(default=0),
        ),
    ]
