# Generated by Django 2.2.3 on 2019-10-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0063_auto_20191022_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='Forming_government_failed',
            field=models.BooleanField(default=False),
        ),
    ]
