# Generated by Django 2.2.3 on 2019-10-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0064_general_forming_government_failed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='general',
            name='Forming_government_failed',
        ),
        migrations.AddField(
            model_name='general',
            name='Status_forming_government',
            field=models.TextField(default=''),
        ),
    ]
