# Generated by Django 2.2.3 on 2019-10-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0066_general_message_propose_deal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='general',
            name='Message_propose_deal',
        ),
        migrations.AddField(
            model_name='parties',
            name='Message_proposal_deal',
            field=models.TextField(default=''),
        ),
    ]
