# Generated by Django 2.2.3 on 2019-10-24 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0067_auto_20191024_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='general',
            name='Message_parliament_page',
        ),
    ]
