# Generated by Django 2.2.3 on 2019-10-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0068_remove_general_message_parliament_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='Message_outcome_proposal_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='general',
            name='Message_outcome_proposal_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='general',
            name='Message_outcome_proposal_3',
            field=models.TextField(default=''),
        ),
    ]
