# Generated by Django 2.2.3 on 2019-10-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0069_auto_20191025_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='parties',
            name='Turn',
            field=models.TextField(default='Not yet'),
        ),
    ]
