# Generated by Django 2.2.3 on 2019-10-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0070_parties_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parties',
            name='Turn',
            field=models.TextField(default=None, null=True),
        ),
    ]
