# Generated by Django 3.1.6 on 2021-02-12 11:20

# This is a DATA MIGRATION
# instead of changing the models this migration adds actual data to the models.

from django.db import migrations

def fill_db(apps, schema_editor):

    # First we create the users
    # For this we need to import the User module
    from django.contrib.auth.models import User

    user1 = User.objects.create_user(username='User1', password='resuresu')
    user1.save()
    user2 = User.objects.create_user(username='User2', password='resuresu')
    user2.save()
    user3 = User.objects.create_superuser(username='Caspar', password='resuresu')
    user3.save()

    # Here we introduce all other existing model / databases.
    # Most are part of the app "Game" but the User-model is retrieved from 'auth'
    # Now User refers to the model/database and not to the module as before
    Parties = apps.get_model('Game', 'Parties')
    Representatives = apps.get_model('Game', 'Representatives')
    Counties = apps.get_model('Game', 'Counties')
    General = apps.get_model('Game', 'General')
    Topics = apps.get_model('Game', 'Topics')
    Deals = apps.get_model('Game', 'Deals')
    User = apps.get_model('auth', 'User')

    # Now add the queries necessary to fill the databases / models.
    Parties.objects.all().delete()
    Parties.objects.bulk_create([
        Parties(Name='Progress party', Next_action=0, Turn="Now", CP=100, LR=0, User=User.objects.get(username="User1"),
                Seats=3, Vote="Yes", Vote_proposal_1="Yes", Vote_proposal_2="No", Vote_proposal_3="No",
                Expected_vote_proposal_1=None, Expected_vote_proposal_2=None, Expected_vote_proposal_3=None,
                Made_deal="No", Deal_breaker=False, Prime_minister=False, Government=False, Declaration_maker="No",
                Declaration_reaction="Rejects"),
        Parties(Name='Conservative union', Next_action=0, Turn="Not yet", CP=-100, LR=0,
                User=User.objects.get(username="User2"), Seats=2, Vote="Yes", Vote_proposal_1="Yes",
                Vote_proposal_2="No", Vote_proposal_3="No", Expected_vote_proposal_1=None,
                Expected_vote_proposal_2=None, Expected_vote_proposal_3=None, Made_deal="No", Deal_breaker=False,
                Prime_minister=False, Government=False, Declaration_maker="No", Declaration_reaction="Rejects"),
        Parties(Name='Ultra Left', Next_action=0, Turn=None, CP=0, LR=-100, User=None, Seats=2, Vote="Yes",
                Vote_proposal_1="No", Vote_proposal_2="No", Vote_proposal_3="No", Expected_vote_proposal_1=None,
                Expected_vote_proposal_2=None, Expected_vote_proposal_3=None, Made_deal="No", Deal_breaker=False,
                Prime_minister=False, Government=False, Declaration_maker="No", Declaration_reaction="Rejects"),
        Parties(Name='Right Point', Next_action=0, Turn=None, CP=0, LR=100, User=None, Seats=2, Vote="Yes",
                Vote_proposal_1="No", Vote_proposal_2="No", Vote_proposal_3="No", Expected_vote_proposal_1=None,
                Expected_vote_proposal_2=None, Expected_vote_proposal_3=None, Made_deal="No", Deal_breaker=False,
                Prime_minister=False, Government=False, Declaration_maker="No", Declaration_reaction="Rejects"),
        Parties(Name='Independent', Next_action=0, Turn=None, CP=0, LR=0, User=None, Seats=0, Vote="Yes",
                Vote_proposal_1="No", Vote_proposal_2="No", Vote_proposal_3="No", Expected_vote_proposal_1=None,
                Expected_vote_proposal_2=None, Expected_vote_proposal_3=None, Made_deal="No", Deal_breaker=False,
                Prime_minister=False, Government=False, Declaration_maker="No", Declaration_reaction="Rejects"),
    ])

    Representatives.objects.all().delete()
    Representatives.objects.bulk_create([
        Representatives(Name='Merita', CP=100, LR=0, Party=Parties.objects.get(Name="Progress party"),
                        County_election="", Percentage=0),
        Representatives(Name='Awiti', CP=90, LR=15, Party=Parties.objects.get(Name="Progress party"),
                        County_election="", Percentage=0),
        Representatives(Name='Jez', CP=80, LR=-20, Party=Parties.objects.get(Name="Progress party"), County_election="",
                        Percentage=0),
        Representatives(Name='Raya', CP=70, LR=25, Party=Parties.objects.get(Name="Progress party"), County_election="",
                        Percentage=0),

        Representatives(Name='Gallus', CP=-100, LR=0, Party=Parties.objects.get(Name="Conservative union"),
                        County_election="", Percentage=0),
        Representatives(Name='Almudena', CP=-90, LR=-25, Party=Parties.objects.get(Name="Conservative union"),
                        County_election="", Percentage=0),
        Representatives(Name='Brynmor', CP=-80, LR=20, Party=Parties.objects.get(Name="Conservative union"),
                        County_election="", Percentage=0),
        Representatives(Name='Patricia', CP=-70, LR=-15, Party=Parties.objects.get(Name="Conservative union"),
                        County_election="", Percentage=0),

        Representatives(Name='Eka', CP=0, LR=-100, Party=Parties.objects.get(Name="Ultra Left"), County_election="",
                        Percentage=0),
        Representatives(Name='Caren', CP=15, LR=-90, Party=Parties.objects.get(Name="Ultra Left"), County_election="",
                        Percentage=0),
        Representatives(Name='Signe', CP=-20, LR=-80, Party=Parties.objects.get(Name="Ultra Left"), County_election="",
                        Percentage=0),
        Representatives(Name='Jannicke', CP=25, LR=-70, Party=Parties.objects.get(Name="Ultra Left"),
                        County_election="", Percentage=0),

        Representatives(Name='Iver', CP=0, LR=100, Party=Parties.objects.get(Name="Right Point"), County_election="",
                        Percentage=0),
        Representatives(Name='Zetenty', CP=-25, LR=90, Party=Parties.objects.get(Name="Right Point"),
                        County_election="", Percentage=0),
        Representatives(Name='Lise', CP=20, LR=80, Party=Parties.objects.get(Name="Right Point"), County_election="",
                        Percentage=0),
        Representatives(Name='Saara', CP=-15, LR=70, Party=Parties.objects.get(Name="Right Point"), County_election="",
                        Percentage=0),
    ])

    Counties.objects.all().delete()
    Counties.objects.bulk_create([
        Counties(Name='University City County', CP=80, LR=0, Spread=5,
                 Representative=Representatives.objects.get(Name="Merita")),
        Counties(Name='Biblebelt County', CP=-80, LR=0, Spread=5,
                 Representative=Representatives.objects.get(Name="Gallus")),
        Counties(Name='Union County', CP=0, LR=-80, Spread=5, Representative=Representatives.objects.get(Name="Eka")),
        Counties(Name='Rich People County', CP=0, LR=80, Spread=5,
                 Representative=Representatives.objects.get(Name="Iver")),

        Counties(Name='Big City County', CP=25, LR=-25, Spread=5,
                 Representative=Representatives.objects.get(Name="Raya")),
        Counties(Name='Pretty Place County', CP=25, LR=25, Spread=5,
                 Representative=Representatives.objects.get(Name="Patricia")),
        Counties(Name='Farm County', CP=-25, LR=25, Spread=5,
                 Representative=Representatives.objects.get(Name="Jannicke")),
        Counties(Name='Factory County', CP=-25, LR=-25, Spread=5,
                 Representative=Representatives.objects.get(Name="Saara")),

        Counties(Name='In The Middle County', CP=0, LR=0, Spread=5,
                 Representative=Representatives.objects.get(Name="Zetenty")),
    ])

    General.objects.all().delete()
    General.objects.bulk_create([
        General(
            Name="Game1",
            Next_action="Submit candidates",
            Year=1,
            Test=True,
            Message_elections_page="Please submit your ballot list",
            Message_outcome_proposal_1="",
            Message_outcome_proposal_2="",
            Message_outcome_proposal_3="",
            Worldview=0,
            Nature=0,
            Ethics=0,
            Taxation=0,
            Social_protection=0,
            Immigration=0,
            LR=0,
            CP=0,
            Worldview_bar=50,
            Nature_bar=50,
            Ethics_bar=50,
            Taxation_bar=50,
            Social_protection_bar=50,
            Immigration_bar=50,
            LR_bar=50,
            CP_bar=50,
            Worldview_govt="",
            Nature_govt="",
            Ethics_govt="",
            Taxation_govt="",
            Social_protection_govt="",
            Immigration_govt="",
            Votes_for_declaration=0,
            Votes_against_declaration=0,
            Status_forming_government="Attempting",
        )
    ])

    Topics.objects.all().delete()
    Topics.objects.bulk_create([
        Topics(Proposal="Invest more in United Nations", Parent="Worldview", Shift=10, New=True, Current_proposal=False,
               Current_proposal_number=1),
        Topics(Proposal="Participate in international peace keeping mission", Parent="Worldview", Shift=10, New=True,
               Current_proposal=False, Current_proposal_number=None),
        Topics(Proposal="Redrawl from international cooperation platform", Parent="Worldview", Shift=-10, New=False,
               Current_proposal=False, Current_proposal_number=None),
        Topics(Proposal="Instate measures to protect national industry", Parent="Worldview", Shift=-10, New=False,
               Current_proposal=False, Current_proposal_number=None),
        Topics(Proposal="Create 3 extra nature reserves", Parent="Nature", Shift=-10, New=False, Current_proposal=False,
               Current_proposal_number=2),
        Topics(Proposal="Extend endangered species list", Parent="Nature", Shift=-10, New=False, Current_proposal=False,
               Current_proposal_number=None),
        Topics(Proposal="Cut rainforest to create space for agriculture", Parent="Nature", Shift=10, New=False,
               Current_proposal=False, Current_proposal_number=None),
        Topics(Proposal="Mark environmmental activists as terrorists", Parent="Nature", Shift=10, New=False,
               Current_proposal=False, Current_proposal_number=None),
        Topics(Proposal="Stimulate a national LHBTI pride day", Parent="Ethics", Shift=10, New=True,
               Current_proposal=False, Current_proposal_number=3),
        Topics(Proposal="Allow abortions further on in pregnancy", Parent="Ethics", Shift=10, New=True,
               Current_proposal=False, Current_proposal_number=None),
        Topics(Proposal="Reduce same sex adoption possibilities", Parent="Ethics", Shift=-10, New=True,
               Current_proposal=False, Current_proposal_number=None),
        Topics(Proposal="Extend traditional values in the constitution", Parent="Ethics", Shift=-10, New=True,
               Current_proposal=False, Current_proposal_number=None),
        Topics(Proposal="Extra tax on the highest earners", Parent="Taxation", Shift=-10, New=True,
               Current_proposal=False, Current_proposal_number=None),
        Topics(Proposal="More tax deductabilities for the poor", Parent="Taxation", Shift=-10, New=True,
               Current_proposal=False, Current_proposal_number=None),
        Topics(Proposal="Lower taxes for all residents", Parent="Taxation", Shift=10, New=False, Current_proposal=True,
               Current_proposal_number=None),
        Topics(Proposal="Decrease taxes on second homes", Parent="Taxation", Shift=10, New=False, Current_proposal=True,
               Current_proposal_number=None),
        Topics(Proposal="Enforce mandatory health care insurance", Parent="Social_protection", Shift=-10, New=True,
               Current_proposal=False, Current_proposal_number=None),
        Topics(Proposal="Increase minium wage", Parent="Social_protection", Shift=-10, New=True, Current_proposal=False,
               Current_proposal_number=None),
        Topics(Proposal="Increase personal responsibility for pension savings", Parent="Social_protection", Shift=10,
               New=True, Current_proposal=False, Current_proposal_number=None),
        Topics(Proposal="Increase commercial stimulants in health care", Parent="Social_protection", Shift=10, New=True,
               Current_proposal=False, Current_proposal_number=None),
        Topics(Proposal="Close the borders for most immigrants", Parent="Immigration", Shift=-10, New=True,
               Current_proposal=False, Current_proposal_number=None),
        Topics(Proposal="Organize a social media anti immigration campaign", Parent="Immigration", Shift=-10, New=True,
               Current_proposal=False, Current_proposal_number=None),
        Topics(Proposal="Less strict access rules for political asylum seekers", Parent="Immigration", Shift=10,
               New=True, Current_proposal=False, Current_proposal_number=None),
        Topics(Proposal="Let more family members of asylumseeker enter the country", Parent="Immigration", Shift=10,
               New=True, Current_proposal=False, Current_proposal_number=None),

    ])

    Deals.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0069_auto_20191025_1043'),
    ]

    operations = [
        migrations.RunPython(fill_db)
    ]

