# Generated by Django 3.1.4 on 2021-02-14 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0074_auto_20210214_1056'),
        ('Game', '0071_auto_20191028_1943'),
    ]

    operations = [
    ]
